# Jupyter Book configuration
title: "Alun's Data Science Portfolio"
author: "Alun Rees"
logo: "_static/images/profile.jpg"

# Execute notebooks configuration
execute:
  execute_notebooks: auto
  timeout: 300
  allow_errors: false

# Sphinx configuration
sphinx:
  config:
    html_title: "Alun's Data Science Portfolio"
    html_logo: "_static/images/profile.jpg"
    html_favicon: "_static/images/profile.jpg"
    html_theme: "sphinx_book_theme"
    html_baseurl: "https://areeslindley.github.io/projects-website/"
    html_theme_options:
      repository_url: https://github.com/areeslindley/projects-website
      use_repository_button: true
      use_issues_button: true
      show_toc_level: 2
      navigation_with_keys: true
      primary_sidebar_end: ["edit-this-page"]
      secondary_sidebar_end: ["sourcelink"]
    html_css_files:
      - css/custom.css

# Bibliography
bibtex_bibfiles:
  - references.bib

# LaTeX
latex:
  latex_documents:
    targetname: book.tex
